baseurl = "https://carsonfong.netlify.app/"
title = "Carson Fong"
author = "Carson"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Carson Fong"

[[menu.main]]
    name = "Home"
    url = "https://carsonfong.netlify.app/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/carsonfong"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/carsonfong"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/carsonfong"
    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
